name: tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '*.md'

permissions:
  contents: read

jobs:
  test:
    name: test ${{ matrix.py }}
    runs-on: ubuntu-latest
    env:
      PA_USERNAME: ${{ secrets.PA_USERNAME }}
      PA_PASSWORD: ${{ secrets.PA_PASSWORD }}
      PA_APP_NAME: ${{ secrets.PA_APP_NAME }}
      PA_TOKEN: ${{ secrets.PA_TOKEN }}
      PA_REGION: ${{ secrets.PA_REGION }}
      PA_CONSOLE_ID: ${{ secrets.PA_CONSOLE_ID }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        py:
          - "3.10"
          - "3.11"
    steps:
      - name: Setup python for tox
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install tox
        run: python -m pip install tox
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Setup test suite
        run: tox r -e py${{ matrix.py }} -vv --notest
      - name: Run test suite
        run: tox r -e py${{ matrix.py }} --skip-pkg-install
